/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as LivingRouteImport } from './routes/living'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RentingRouteImport } from './routes/renting'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingRoute = LivingRouteImport.update({
  id: '/living',
  path: '/living',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RentingRoute = RentingRouteImport.update({
  id: '/renting',
  path: '/renting',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/investing': typeof InvestingRoute
  '/living': typeof LivingRoute
  '/portfolio': typeof PortfolioRoute
  '/renting': typeof RentingRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/investing': typeof InvestingRoute
  '/living': typeof LivingRoute
  '/portfolio': typeof PortfolioRoute
  '/renting': typeof RentingRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/investing': typeof InvestingRoute
  '/living': typeof LivingRoute
  '/portfolio': typeof PortfolioRoute
  '/renting': typeof RentingRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/investing'
    | '/living'
    | '/portfolio'
    | '/renting'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/investing'
    | '/living'
    | '/portfolio'
    | '/renting'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/investing'
    | '/living'
    | '/portfolio'
    | '/renting'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  InvestingRoute: typeof InvestingRoute
  LivingRoute: typeof LivingRoute
  PortfolioRoute: typeof PortfolioRoute
  RentingRoute: typeof RentingRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/living': {
      id: '/living'
      path: '/living'
      fullPath: '/living'
      preLoaderRoute: typeof LivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renting': {
      id: '/renting'
      path: '/renting'
      fullPath: '/renting'
      preLoaderRoute: typeof RentingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  InvestingRoute: InvestingRoute,
  LivingRoute: LivingRoute,
  PortfolioRoute: PortfolioRoute,
  RentingRoute: RentingRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
