/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LangChar125RouteRouteImport } from './routes/{-$lang}/route'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125ContactRouteImport } from './routes/{-$lang}/contact'
import { Route as Char123LangChar125InvestingRouteImport } from './routes/{-$lang}/investing'
import { Route as Char123LangChar125LivingRouteImport } from './routes/{-$lang}/living'
import { Route as Char123LangChar125PortfolioRouteImport } from './routes/{-$lang}/portfolio'
import { Route as Char123LangChar125RentingRouteImport } from './routes/{-$lang}/renting'
import { Route as Char123LangChar125TeamRouteImport } from './routes/{-$lang}/team'
import { Route as Char123LangChar125PortfolioSlugRouteImport } from './routes/{-$lang}/portfolio_.$slug'

const Char123LangChar125RouteRoute = Char123LangChar125RouteRouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125ContactRoute =
  Char123LangChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125InvestingRoute =
  Char123LangChar125InvestingRouteImport.update({
    id: '/investing',
    path: '/investing',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125LivingRoute =
  Char123LangChar125LivingRouteImport.update({
    id: '/living',
    path: '/living',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125PortfolioRoute =
  Char123LangChar125PortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125RentingRoute =
  Char123LangChar125RentingRouteImport.update({
    id: '/renting',
    path: '/renting',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125TeamRoute = Char123LangChar125TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125PortfolioSlugRoute =
  Char123LangChar125PortfolioSlugRouteImport.update({
    id: '/portfolio_/$slug',
    path: '/portfolio/$slug',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/investing': typeof Char123LangChar125InvestingRoute
  '/{-$lang}/living': typeof Char123LangChar125LivingRoute
  '/{-$lang}/portfolio': typeof Char123LangChar125PortfolioRoute
  '/{-$lang}/renting': typeof Char123LangChar125RentingRoute
  '/{-$lang}/team': typeof Char123LangChar125TeamRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/portfolio/$slug': typeof Char123LangChar125PortfolioSlugRoute
}
export interface FileRoutesByTo {
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/investing': typeof Char123LangChar125InvestingRoute
  '/{-$lang}/living': typeof Char123LangChar125LivingRoute
  '/{-$lang}/portfolio': typeof Char123LangChar125PortfolioRoute
  '/{-$lang}/renting': typeof Char123LangChar125RentingRoute
  '/{-$lang}/team': typeof Char123LangChar125TeamRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/portfolio/$slug': typeof Char123LangChar125PortfolioSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/investing': typeof Char123LangChar125InvestingRoute
  '/{-$lang}/living': typeof Char123LangChar125LivingRoute
  '/{-$lang}/portfolio': typeof Char123LangChar125PortfolioRoute
  '/{-$lang}/renting': typeof Char123LangChar125RentingRoute
  '/{-$lang}/team': typeof Char123LangChar125TeamRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/portfolio_/$slug': typeof Char123LangChar125PortfolioSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/{-$lang}/contact'
    | '/{-$lang}/investing'
    | '/{-$lang}/living'
    | '/{-$lang}/portfolio'
    | '/{-$lang}/renting'
    | '/{-$lang}/team'
    | '/{-$lang}/'
    | '/{-$lang}/portfolio/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$lang}/contact'
    | '/{-$lang}/investing'
    | '/{-$lang}/living'
    | '/{-$lang}/portfolio'
    | '/{-$lang}/renting'
    | '/{-$lang}/team'
    | '/{-$lang}'
    | '/{-$lang}/portfolio/$slug'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/{-$lang}/contact'
    | '/{-$lang}/investing'
    | '/{-$lang}/living'
    | '/{-$lang}/portfolio'
    | '/{-$lang}/renting'
    | '/{-$lang}/team'
    | '/{-$lang}/'
    | '/{-$lang}/portfolio_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125RouteRoute: typeof Char123LangChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/contact': {
      id: '/{-$lang}/contact'
      path: '/contact'
      fullPath: '/{-$lang}/contact'
      preLoaderRoute: typeof Char123LangChar125ContactRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/investing': {
      id: '/{-$lang}/investing'
      path: '/investing'
      fullPath: '/{-$lang}/investing'
      preLoaderRoute: typeof Char123LangChar125InvestingRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/living': {
      id: '/{-$lang}/living'
      path: '/living'
      fullPath: '/{-$lang}/living'
      preLoaderRoute: typeof Char123LangChar125LivingRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/portfolio': {
      id: '/{-$lang}/portfolio'
      path: '/portfolio'
      fullPath: '/{-$lang}/portfolio'
      preLoaderRoute: typeof Char123LangChar125PortfolioRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/renting': {
      id: '/{-$lang}/renting'
      path: '/renting'
      fullPath: '/{-$lang}/renting'
      preLoaderRoute: typeof Char123LangChar125RentingRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/team': {
      id: '/{-$lang}/team'
      path: '/team'
      fullPath: '/{-$lang}/team'
      preLoaderRoute: typeof Char123LangChar125TeamRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/portfolio_/$slug': {
      id: '/{-$lang}/portfolio_/$slug'
      path: '/portfolio/$slug'
      fullPath: '/{-$lang}/portfolio/$slug'
      preLoaderRoute: typeof Char123LangChar125PortfolioSlugRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
  }
}

interface Char123LangChar125RouteRouteChildren {
  Char123LangChar125ContactRoute: typeof Char123LangChar125ContactRoute
  Char123LangChar125InvestingRoute: typeof Char123LangChar125InvestingRoute
  Char123LangChar125LivingRoute: typeof Char123LangChar125LivingRoute
  Char123LangChar125PortfolioRoute: typeof Char123LangChar125PortfolioRoute
  Char123LangChar125RentingRoute: typeof Char123LangChar125RentingRoute
  Char123LangChar125TeamRoute: typeof Char123LangChar125TeamRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125PortfolioSlugRoute: typeof Char123LangChar125PortfolioSlugRoute
}

const Char123LangChar125RouteRouteChildren: Char123LangChar125RouteRouteChildren =
  {
    Char123LangChar125ContactRoute: Char123LangChar125ContactRoute,
    Char123LangChar125InvestingRoute: Char123LangChar125InvestingRoute,
    Char123LangChar125LivingRoute: Char123LangChar125LivingRoute,
    Char123LangChar125PortfolioRoute: Char123LangChar125PortfolioRoute,
    Char123LangChar125RentingRoute: Char123LangChar125RentingRoute,
    Char123LangChar125TeamRoute: Char123LangChar125TeamRoute,
    Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
    Char123LangChar125PortfolioSlugRoute: Char123LangChar125PortfolioSlugRoute,
  }

const Char123LangChar125RouteRouteWithChildren =
  Char123LangChar125RouteRoute._addFileChildren(
    Char123LangChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125RouteRoute: Char123LangChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
